apiVersion: apps/v1
kind: Deployment
metadata:
  name: petclinic
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.petclinic.replicas }}
  selector:
    matchLabels:
      app: petclinic
  template:
    metadata:
      labels:
        app: petclinic
      annotations:
        instrumentation.opentelemetry.io/inject-java: "true"
    spec:
      containers:
      - name: petclinic
        image: {{ .Values.petclinic.image }}
        ports:
        - containerPort: 8080
        env:
        - name: SPRING_DATASOURCE_URL
          value: jdbc:sqlserver://sqlserver:1433;databaseName={{ .Values.sqlserver.database }};encrypt=false
        - name: SPRING_DATASOURCE_USERNAME
          value: sa
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: sqlserver-secret
              key: SA_PASSWORD
