apiVersion: v1
kind: Service
metadata:
  name: mssql
  namespace: {{ .Values.namespace }}
spec:
  type: {{ .Values.mssql.service.type }}
  ports:
    - port: {{ .Values.mssql.service.port }}
      targetPort: 1433
  selector:
    app: mssql
